export const practiceData: Record<string, { title: string; description: string; details: string[]; image: string }> = {
  "supreme-court-litigation": {
    title: "Supreme Court Practice",
    description: "Satyarup Law Firm regularly handles matters before the Supreme Court of India. As an Advocate-on-Record practice, the firm provides complete procedural and litigation support, including drafting, filing, and representation.",
    details: ["Special Leave Petitions", "Civil Appeals", "Criminal Appeals", "Constitutional Matters", "Arbitration-related Litigation", "Writ Petitions", "Review & Curative Petitions"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80",
  },
  "high-court-litigation": {
    title: "High Court Litigation",
    description: "The firm appears before several High Courts across India, handling original and appellate matters across civil, criminal, and commercial law.",
    details: ["Delhi High Court", "Bombay High Court", "Punjab & Haryana High Court", "Madhya Pradesh High Court", "Patna High Court", "Tripura High Court", "Original & Appellate Jurisdiction"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
  },
  "civil-criminal-litigation": {
    title: "Civil & Criminal Litigation",
    description: "High-quality advocacy in civil suits, writ petitions, and appeals; criminal defense and white-collar crime prosecution/defense; specialist teams for complex commercial, corporate, and regulatory litigation across courts and tribunals.",
    details: ["Civil Suits & Recovery Matters", "Property Disputes & Injunctions", "Criminal Defense & Prosecution", "Bail Applications", "White-Collar Crime", "Trial & Appellate Proceedings", "Writ Petitions", "Complex Commercial Litigation"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80",
  },
  "arbitration-dispute-resolution": {
    title: "Arbitration & Alternative Dispute Resolution",
    description: "The firm has extensive experience in domestic and international arbitration (institutional and ad-hoc), enforcement of arbitral awards, mediation and negotiation. Dr. Ashwani Bhardwaj has served as an arbitrator on the panel of the Delhi International Arbitration Centre.",
    details: ["Domestic & International Arbitration", "Institutional & Ad-hoc Arbitration", "Enforcement of Arbitral Awards", "Mediation & Negotiation", "Arbitration-related Court Proceedings", "Contractual Dispute Resolution", "Commercial Arbitration", "Proceedings under Arbitration & Conciliation Act"],
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
  },
  "corporate-commercial-law": {
    title: "Corporate & Commercial Law",
    description: "We advise businesses of all sizes on incorporation, corporate governance, shareholders' agreements, joint ventures, M&A, private equity, venture capital, cross-border transactions, and corporate restructuring. Our corporate team drafts and negotiates complex commercial contracts, advises on regulatory compliance, and represents clients before tribunals, the National Company Law Tribunal (NCLT) and High Courts.",
    details: ["Incorporation & Corporate Governance", "Shareholders' Agreements & Joint Ventures", "Private Equity & Venture Capital", "Cross-border Transactions", "Corporate Restructuring", "NCLT Representation", "Regulatory Compliance", "Commercial Contract Drafting & Negotiation"],
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=80",
  },
  "mergers-acquisitions": {
    title: "Mergers & Acquisitions",
    description: "Full-service M&A support: due diligence, deal structuring, SPA negotiation, regulatory filings (FDI, RBI, Competition Commission clearances), and post-merger integration. We bring cross-disciplinary expertise (tax, IP, employment) to reduce deal risk and speed execution.",
    details: ["Due Diligence", "Deal Structuring", "SPA Negotiation", "FDI & RBI Regulatory Filings", "Competition Commission Clearances", "Post-Merger Integration", "Cross-disciplinary Advisory (Tax, IP, Employment)"],
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&auto=format&fit=crop&q=80",
  },
  "insolvency-bankruptcy": {
    title: "Insolvency & Bankruptcy (IBC)",
    description: "Representation in insolvency resolution processes under the Insolvency & Bankruptcy Code, creditor/debtor strategy, CIRP proceedings, appeal practice before the NCLAT and Supreme Court, and restructuring/rehabilitation advice to stressed corporates.",
    details: ["CIRP Proceedings", "Creditor & Debtor Strategy", "NCLAT Appeals", "Supreme Court IBC Matters", "Corporate Restructuring & Rehabilitation", "Liquidation Proceedings", "Voluntary Liquidation"],
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&auto=format&fit=crop&q=80",
  },
  "banking-financial-litigation": {
    title: "Banking & Finance",
    description: "Lending, syndicated loans, project finance, structured finance, securities enforcements, recovery proceedings, and regulatory advice for banks, NBFCs and fintech firms. We handle documentation, enforcement, and disputes arising from financial transactions.",
    details: ["Bank of Baroda", "Punjab National Bank", "Central Bank of India", "Indian Overseas Bank", "Lending & Syndicated Loans", "Project & Structured Finance", "Recovery Proceedings", "NBFC & Fintech Regulatory Advice"],
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=80",
  },
  "securities-capital-markets": {
    title: "Securities & Capital Markets",
    description: "Advice on IPOs, private placements, compliance with SEBI regulations, takeovers and delisting matters, securities litigation, and representation before SEBI and market regulators.",
    details: ["IPO Advisory", "Private Placements", "SEBI Compliance", "Takeovers & Delisting", "Securities Litigation", "Representation before SEBI", "Market Regulator Matters"],
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&auto=format&fit=crop&q=80",
  },
  "taxation": {
    title: "Taxation (Direct & Indirect)",
    description: "Strategic tax planning, litigation and representation before Income Tax Appellate Tribunal (ITAT), GST advisory and litigation, customs duty disputes, transfer pricing and tax structuring for transactions.",
    details: ["Income Tax Planning & Litigation", "ITAT Representation", "GST Advisory & Litigation", "Customs Duty Disputes", "Transfer Pricing", "Tax Structuring for Transactions", "International Taxation"],
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&auto=format&fit=crop&q=80",
  },
  "competition-antitrust": {
    title: "Competition (Antitrust) Law",
    description: "Counsel on Competition Commission of India (CCI) filings, merger control, abuse-of-dominance issues, cartel investigations, compliance audits, and defense in CCI proceedings.",
    details: ["CCI Filings", "Merger Control", "Abuse of Dominance", "Cartel Investigations", "Compliance Audits", "Defense in CCI Proceedings", "Anti-competitive Agreement Advisory"],
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
  },
  "contract-drafting-commercial-disputes": {
    title: "Contract Drafting & Commercial Disputes",
    description: "Drafting, reviewing and negotiating commercial agreements (supply, distribution, franchise, services, outsourcing). Litigation and arbitration for breach of contract, enforcement of contractual rights and remedies.",
    details: ["Supply & Distribution Agreements", "Franchise Agreements", "Services & Outsourcing Contracts", "Breach of Contract Litigation", "Enforcement of Contractual Rights", "Commercial Arbitration", "Contract Review & Negotiation"],
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
  },
  "government-regulatory-matters": {
    title: "Government & Public Sector Representation",
    description: "The firm has represented the Union of India and various public sector entities. Such matters frequently involve complex statutory interpretation, policy issues, administrative law, and constitutional matters.",
    details: ["Union of India", "Ministry of Railways", "Western Coalfields Limited", "Shipping Corporation of India", "Association of Indian Universities", "Statutory Interpretation", "Administrative Law", "Public & Administrative Law"],
    image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80",
  },
  "employment-labour-law": {
    title: "Employment & Labour Law",
    description: "Advice on employment contracts, compliance with labour statutes, standing before labour courts/tribunals, retrenchment and settlement, ESOPs and employee regulation matters.",
    details: ["Employment Contracts", "Labour Statute Compliance", "Labour Court & Tribunal Representation", "Retrenchment & Settlement", "ESOPs & Employee Regulations", "Workplace Dispute Resolution", "Labour Code Advisory"],
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80",
  },
  "real-estate-construction": {
    title: "Real Estate & Construction",
    description: "Transaction advice, title due diligence, large-scale project documentation, sale/lease agreements, RERA compliance, condominium/developer disputes, construction contracts and delay claims.",
    details: ["Title Due Diligence", "Sale & Lease Agreements", "RERA Compliance", "Developer & Condominium Disputes", "Construction Contracts", "Delay Claims", "Large-scale Project Documentation"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&auto=format&fit=crop&q=80",
  },
  "intellectual-property": {
    title: "Intellectual Property (IP)",
    description: "Comprehensive IP services: patent drafting & prosecution, trademark filing & enforcement, copyright matters, domain disputes, IP licensing, portfolio management and IP litigation.",
    details: ["Patent Drafting & Prosecution", "Trademark Filing & Enforcement", "Copyright Matters", "Domain Disputes", "IP Licensing", "Portfolio Management", "IP Litigation"],
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=80",
  },
  "data-protection-it-law": {
    title: "Data Protection, Privacy & IT Law",
    description: "Advisory and compliance for data protection laws, cross-border data transfer policies, IT contracts, cybersecurity incidents, and representation in regulatory or breach-related disputes.",
    details: ["Data Protection Compliance", "Cross-border Data Transfer Policies", "IT Contracts", "Cybersecurity Incident Response", "Digital Personal Data Protection Framework", "Regulatory Disputes", "Privacy Advisory"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
  },
  "environmental-energy-law": {
    title: "Environmental & Energy Law",
    description: "Regulatory advice and litigation on environmental clearances, renewable energy projects, power purchase agreements, regulations for oil & gas, and compliance before pollution control boards and tribunals.",
    details: ["National Green Tribunal Matters", "Environmental Clearances", "Renewable Energy Projects", "Power Purchase Agreements", "Oil & Gas Regulations", "Pollution Control Board Compliance", "Coastal & Environmental Regulatory Compliance"],
    image: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=1200&auto=format&fit=crop&q=80",
  },
  "maritime-shipping-admiralty": {
    title: "Maritime, Shipping & Admiralty",
    description: "Maritime & Shipping Law is a core specialty. We offer end-to-end services for shipowners, charterers, cargo interests, P&I Clubs, insurers, ports, terminals, shipyards and logistics providers.",
    details: ["Charterparties & Bills of Lading", "Cargo Claims (Loss, Damage, Delay)", "Collision, Salvage & General Average", "Towage, Pilotage & Port Liabilities", "Arrest & Sale of Vessels", "Ship Mortgages & Maritime Liens", "Marine Insurance Disputes", "Crew Matters & Seafarer Welfare", "Admiralty Jurisdiction Matters", "Ship Finance, Sale & Purchase"],
    image: "https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?w=1200&auto=format&fit=crop&q=80",
  },
  "aviation-transport-logistics": {
    title: "Aviation, Transport & Logistics",
    description: "Regulatory advice, liability and claims, contracts (charter-party, bills of lading), cargo disputes, salvage/towage claims, port and terminal agreements, and cross-border transport regulation.",
    details: ["Aviation Regulatory Advisory", "Transport Liability & Claims", "Cargo Disputes", "Port & Terminal Agreements", "Cross-border Transport Regulation", "Logistics Contracts", "Regulatory Compliance"],
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=1200&auto=format&fit=crop&q=80",
  },
  "insurance-reinsurance": {
    title: "Insurance & Reinsurance",
    description: "Advice on policy drafting, claim handling, coverage disputes, marine insurance, general insurance litigation, and representation before insurance tribunals and courts.",
    details: ["Policy Drafting", "Claim Handling", "Coverage Disputes", "Marine Insurance", "General Insurance Litigation", "Insurance Tribunal Representation", "Reinsurance Advisory"],
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
  },
  "customs-foreign-trade-fema": {
    title: "Customs, Foreign Trade & FEMA",
    description: "Trade remedy matters, customs litigation, import-export compliance, FDI structuring, FEMA advisory and enforcement.",
    details: ["Trade Remedy Matters", "Customs Litigation", "Import-Export Compliance", "FDI Structuring", "FEMA Advisory & Enforcement", "Foreign Exchange Regulations", "Cross-border Trade Compliance"],
    image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80",
  },
  "white-collar-crime-compliance": {
    title: "White-Collar Crime, Compliance & Investigations",
    description: "Internal investigations, anti-corruption compliance, FSC/SEBI/FEMA/NDPS/PC Act matters, and defense in criminal and regulatory probes.",
    details: ["Internal Investigations", "Anti-corruption Compliance", "SEBI & FEMA Matters", "Prevention of Corruption Act", "NDPS Act Matters", "Regulatory Probes Defense", "Corporate Compliance Programs"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80",
  },
  "family-law": {
    title: "Family Law & Personal Matters",
    description: "Divorce, maintenance, child custody & adoption, family settlements, and related litigation in family courts and civil courts.",
    details: ["Divorce Proceedings", "Maintenance & Alimony", "Child Custody & Adoption", "Family Settlements", "Domestic Violence Matters", "Succession & Inheritance", "Family Court Litigation"],
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80",
  },
  "consumer-protection": {
    title: "Competition & Consumer Protection",
    description: "Representation in consumer disputes, product liability, class suits, investigations under consumer protection laws and regulatory compliance for consumer-facing businesses.",
    details: ["Consumer Dispute Redressal", "Product Liability", "Class Suits", "Consumer Protection Investigations", "NCDRC Representation", "State & District Consumer Commissions", "Regulatory Compliance"],
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80",
  },
  "education-health-regulatory": {
    title: "Education, Health & Regulatory Compliance",
    description: "Advice and representation for regulated sectors — licensing, accreditation, compliance, and disputes in education and healthcare sectors.",
    details: ["Licensing & Accreditation", "Education Sector Compliance", "Healthcare Regulatory Matters", "Sectoral Disputes", "Regulatory Advisory", "Institutional Compliance"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
  },
  "trust-society-nonprofit": {
    title: "Trust, Society & Nonprofit Law",
    description: "Formation and regulation of trusts, societies and charitable institutions, fundraising compliance, foreign contribution regulation (FCRA) advisory.",
    details: ["Trust Formation & Registration", "Society Registration", "Charitable Institution Regulation", "Fundraising Compliance", "FCRA Advisory", "NGO Compliance", "Tax Exemption Matters"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
  },
};

export const articleData: Record<string, { title: string; date: string; category: string; image: string; content: string }> = {
  "supreme-court-corporate-governance": {
    title: "Supreme Court Landmark Ruling on Corporate Governance",
    date: "February 10, 2026",
    category: "Constitutional Law",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80",
    content: `The Supreme Court of India has delivered a landmark judgment that fundamentally reshapes corporate governance standards for listed companies. The ruling establishes new precedents for how boards of directors must approach their fiduciary duties, particularly in matters involving related-party transactions and minority shareholder protection.\n\nThe judgment, which arose from a dispute involving a major conglomerate, clarifies the scope of director liability and introduces stricter standards for board oversight. Companies must now demonstrate that their governance frameworks actively protect shareholder interests.\n\nKey takeaways include enhanced disclosure obligations, stricter conflict-of-interest protocols, and a new standard for assessing board member independence.\n\nSatyarup Law Firm continues to advise clients on the implications of this ruling and assist in updating governance frameworks to ensure compliance.`,
  },
  "labour-code-amendments": {
    title: "New Amendments to Labour Code: What Employers Must Know",
    date: "February 5, 2026",
    category: "Regulatory Law",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
    content: `The Government of India has introduced significant amendments to the consolidated Labour Codes that will impact employers across all industries. These changes, effective from April 2026, affect hiring practices, working hours, employee benefits, and dispute resolution mechanisms.\n\nAmong the most significant changes are revised overtime calculations, mandatory electronic record-keeping, and enhanced protections for gig and platform workers. Employers with more than 50 employees will also need to establish formal grievance redressal committees.\n\nThe amendments expand social security coverage to previously excluded categories of workers, representing a major shift in India's labour law landscape.\n\nSatyarup Law Firm is conducting detailed advisory sessions for institutional and corporate clients to help them implement the required changes before the April deadline.`,
  },
  "ip-digital-age": {
    title: "Protecting Your Intellectual Property in the Digital Age",
    date: "January 28, 2026",
    category: "IP Law",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=80",
    content: `As digital transformation accelerates across industries, protecting intellectual property has become more complex and more critical than ever before. From software patents to digital trademarks and online copyright enforcement, the landscape of IP protection demands a nuanced understanding of both technology and law.\n\nThe proliferation of AI-generated content, blockchain-based digital assets, and cross-border digital commerce presents novel challenges for IP holders. Indian courts and tribunals are increasingly called upon to adjudicate disputes involving digital intellectual property, requiring practitioners to stay abreast of evolving jurisprudence.\n\nKey areas of concern include trademark infringement on e-commerce platforms, copyright issues surrounding user-generated content, patent trolling in the technology sector, and the protection of trade secrets in remote working environments.\n\nSatyarup Law Firm advises clients on comprehensive IP protection strategies, including preventive measures, registration, licensing, and enforcement through litigation before the appropriate courts and tribunals.`,
  },
  "rera-compliance-2026": {
    title: "Real Estate Market Update: RERA Compliance Changes for 2026",
    date: "January 20, 2026",
    category: "Property Law",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&auto=format&fit=crop&q=80",
    content: `The Real Estate (Regulation and Development) Act, 2016, continues to evolve with significant amendments proposed for implementation in 2026. These changes aim to strengthen buyer protection, enhance transparency in real estate transactions, and streamline the dispute resolution process before RERA authorities.\n\nNotable amendments include stricter timelines for project completion, enhanced penalties for non-compliance by developers, and new provisions for the registration and regulation of real estate agents. The amendments also introduce digital compliance requirements, mandating online disclosure of project details and financial records.\n\nFor buyers and investors, these changes represent a significant strengthening of consumer protection in real estate. For developers and builders, the amendments necessitate a thorough review of compliance frameworks and internal processes.\n\nSatyarup Law Firm provides advisory services on RERA compliance, assisting developers, buyers, and institutions in navigating the regulatory framework and resolving disputes before the appropriate authorities.`,
  },
  "cyber-crime-laws-india": {
    title: "Understanding Cyber Crime Laws in India",
    date: "January 15, 2026",
    category: "Criminal Law",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
    content: `India's cyber crime legislation, primarily governed by the Information Technology Act, 2000, and its subsequent amendments, provides the legal framework for addressing digital offences. With the increasing digitisation of commerce, governance, and personal communications, understanding these laws has become essential for individuals and businesses alike.\n\nThe legal landscape covers a broad spectrum of offences including identity theft, data breaches, online fraud, cyber stalking, defamation through electronic means, and unauthorised access to computer systems. Recent judicial pronouncements have further clarified the scope and application of these provisions.\n\nFor businesses, compliance with data protection norms and cybersecurity requirements has become a critical operational concern. The proposed Digital Personal Data Protection framework adds additional obligations for data controllers and processors.\n\nSatyarup Law Firm handles criminal matters involving cyber offences, representing clients before courts and tribunals in proceedings under the IT Act and related criminal statutes. The firm also provides advisory services on cybersecurity compliance and data protection.`,
  },
  "firm-expansion-2026": {
    title: "Satyarup Law Firm: A Year of Continued Growth",
    date: "January 8, 2026",
    category: "Firm News",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
    content: `Satyarup Law Firm begins 2026 with a renewed commitment to delivering high-quality legal representation across its core practice areas. Building on three decades of litigation experience, the firm continues to strengthen its capabilities in Supreme Court litigation, arbitration, banking and financial disputes, and government representation.\n\nThe firm's practice before the Supreme Court of India remains central to its operations, with Dr. Ashwani Bhardwaj continuing to handle significant matters as Advocate-on-Record. The firm's appearances before multiple High Courts across India ensure comprehensive geographical coverage for its institutional and corporate clients.\n\nNotably, the firm's arbitration practice has seen sustained growth, with an increasing number of commercial and government-related disputes being referred to arbitration. Dr. Bhardwaj's role as an arbitrator on the panel of the Delhi International Arbitration Centre reflects the firm's deep expertise in this area.\n\nSatyarup Law Firm remains committed to its founding principles of preparation, clarity, integrity, and commitment in all matters undertaken.`,
  },
};

export const practiceSlugs = Object.keys(practiceData);
export const articleSlugs = Object.keys(articleData);
